  #### Terraform Deploy
  - name: Create gitignore for Terraform working files
    ansible.builtin.copy:
      dest: /{{ working_dir }}/{{ tf_build }}/.gitignore
      content: |
        .terraform
        .terraform.lock.hcl          
  - name: Creating Terraform IoC
    block:
      - name: Initialize Terraform Provider
        cloud.terraform.terraform:
          project_path: /{{ working_dir }}/{{ tf_build }}
          state: present
          force_init: true
        register: deployed_tf
  - name: Allowing AWS time to spin up instance
    ansible.builtin.pause:
      minutes: 1