- name: Create incident
  servicenow.itsm.incident:
    instance:
      host: https://dev194811.service-now.com/
      username: {{ servicenow_username }}
      password: {{ servicenow_password }}
    state: new
    caller: some.user
    short_description: User is not receiving email
    description: User has been unable to receive email for the past 15 minutes
    impact: low
    urgency: low