---
- name: listen for tfc pre plan run task events
  hosts: all

  rules:
    - name: pre plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true