---
- name: listen for tfc pre apply run task events
  hosts: all
  rules:
    - name: post plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true