---
- name: listen for tfc pre plan run task events
  hosts: all
  sources:
    - name: hcp terraform runtask preplan
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        hmac_secret: '{{ tf_hmac_runtask }}'
        hmac_header: 'X-TFC-Task-Signature'
        hmac_format: hex
        hmac_algo: sha512
  rules:
    - name: pre plan status rule
      condition: true
      actions:
        - print_event:
           pretty: true