---
- name: listen for tfc post apply run task events
  hosts: all
  rules:
    - name: post apply status rule
      condition: event.payload.stage == "post_apply"
      actions:
        - print_event:
           pretty: true
        - run_job_template:
            name: Post Apply Run Task
            organization: Default
            job_args:
              extra_vars:
                access_token: "{{ event.payload.access_token }}"
                task_result_callback_url: "{{ event.payload.task_result_callback_url }}"
                workspace: "{{ event.payload.workspace_id }}"