---
- name: listen for tfc pre plan run task events
  hosts: all
  sources:
    - name: tfc run task webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        # need a custom de with certs baked in for this to work
        certfile: /opt/tls/custom/fullchain.pem
        keyfile: /opt/tls/custom/key.pem
  rules:
    - name: post plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true