---
- name: listen for tfc post plan run task events
  hosts: all
  sources:
    - name: hcp terraform runtask postplan
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
        hmac_secret: "{{ tf_hmac_runtask }}"
        hmac_header: 'X-TFC-Task-Signature'
        hmac_format: hex
        hmac_algo: sha512
  rules:
    - name: post plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true
        - run_job_template:
            name: Post Plan Run Task
            organization: Default
            job_args:
              extra_vars:
                access_token: "{{ event.payload.access_token }}"
                task_result_callback_url: "{{ event.payload.task_result_callback_url }}"
                workspace: "{{ event.payload.workspace_id}}"              