---
- name: listen for tfc pre apply run task events
  hosts: all
  sources:
    - name: hcp terraform runtask pre-apply
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
        hmac_secret: "{{ hmac_secret }}"
        hmac_header: 'X-TFC-Task-Signature'
        hmac_format: hex
        hmac_algo: sha512
  rules:
    - name: post plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true