---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
  - role: terraform-state

- hosts: "{{ hostvars['localhost']['public_dns'] | default('host_does_not_exist')}}"
  gather_facts: true
  tasks:
    - name: include tasks to execute against target hosts
      block:    
        - name: include mock-vm-setup role
          ansible.builtin.include_role:
            name: mock-vm-setup
        - name: set success status and message
          ansible.builtin.set_fact:
            completed_run_task_status: passed
            completed_run_task_message: ansible eda post plan run task completed succesfully
      rescue:
        - name: set failure status and message
          ansible.builtin.set_fact:
            completed_run_task_status: failed
            completed_run_task_message: ansible eda post plan run task encountered and issue. check the controller logs for details
        
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
  - role: run-task-response
    vars:
      run_task_status: "{{ hostvars[public_dns]['completed_run_task_status']  }}"
      run_task_message: "{{ hostvars[public_dns]['completed_run_task_message'] }}"
    when: public_dns is defined
  - role: run-task-response
    vars:
      run_task_status: "passed"
      run_task_message: "ansible eda post plan run task completed, although no hosts were matched and no actions were taken"
    when: public_dns is not defined